### ISSUE TITLE
Something to improve

### ISSUE THREAD

**Issue by MaxNeira** [josuemeza/SwiftyEssentials#1]
You could add more methods to the String class, for example getSubstring like in Java or Android.

**Comment by josuemeza** [comment]
On Java, the substring method allow one or two parameters. [Java substring doc.](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int))
For example:
- One parameter:
```java
String str = "Lorem ipsum";
System.out.println(str.substring(6)); // Prints: "ipsum"
```
- Two parameters:
```java
String str = "Lorem ipsum";
System.out.println(str.substring(0,5)); // Prints: "Lorem"
```
On SwiftyEssentials you can use the defined subscript of String for one parameter substring.

```swift
let str = "Lorem ipsum"
print(str[0..<5]) // Prints: "Lorem"
```
For the two parameters substring method, in Swift 4, you can use an open range:

```swift
let str = "Lorem ipsum"
print(str[6>..]) // Prints: "ipsum"
```

but on Swift <4 it is not possible and I working to fix it.
